/*******************************************************************************
 * Copyright (c) 2007 Matteo Baccan <matteo@baccan.it>
 *
 * This program and the accompanying materials are made available under the
 * terms of the Common Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors: Matteo Baccan - initial implementation
 ******************************************************************************/

import java.net.*;
import java.io.*;
import java.util.*;

public class ChuckNorris {

    public static void main(String[] args) {
       ChuckNorris gr = new ChuckNorris();
       System.out.println( gr.getNorris() );
    }

    public String getNorris() {
        String cRet = "";
        try {
           double random = (double) Math.random()*chuck.length;
           if (random >= chuck.length) {
             random=0;
           }
           cRet = chuck[(int)random];
        } catch (Throwable e){
           //
        }

        return cRet;
    }

String[] chuck = {
"A Carnevale, Zorro si traveste da Chuck Norris.",
"A Chuck Norris i biscotti nel the' non si spappolano.",
"A Chuck Norris non piace fare la coda. Per ovviare a questo problema, qualcuno potrebbe pensare che prenda chi gli sta davanti a calci rotanti in faccia e passi. Invece no. Chuck Norris aspetta il suo turno come tutti gli altri con il solo scopo di accumulare rabbia e adrenalina, poi fa quello che deve fare e solo in seguito rintraccia chi gli stava davanti uno ad uno e gli ruba l'anima a morsi.",
"A Chuck Norris non piace lo Zoo, perche' considera ingiusto rinchiudere gli animali nelle gabbie. Invece di ucciderli a calci rotanti come tutti gli altri esseri viventi.",
"A Las Vegas, Chuck Norris ha giocato il 101 giallo alla roulette. E ha vinto.",
"A Los Angeles '84, Chuck Norris getto' il peso a 6.11 metri. Poi i giudici controllarono le riprese tv, e si accorsero che la misura esatta era una circonferenza terrestre+6.11 metri.",
"A morra cinese, Chuck Norris sconfigge carta, forbice e sasso contemporaneamente.",
"Ad aspettare nello spogliatoio dello stadio di Istanbul i giocatori del Liverpool, a fine primo tempo della finale di Champions League del 2005, c'era Chuck Norris.",
"Agnelli portava l'orologio sopra al polsino, Chuck Norris le palle sopra ai boxer.",
"Al Qaeda ha dichiarato guerra a tutto il mondo occidentale, tranne che a Chuck Norris.",
"Alcuni film di Chuck Norris sono talmente violenti che gli adulti dovrebbero vederli solo in presenza di Chuck Norris.",
"All'inizio dei tempi c'era il nulla. Poi arrivo' Chuck Norris, colpi' con un calcio rotante il nulla e gli disse 'muovi il culo!'. Questa e' la storia dell'universo.",
"All'ultima persona che ha provato ad entrare nel nostro blog usando la password 'chucknorris' e' stata asportata la faccia da un calcio rotante di Chuck Norris ed e' stata utilizzata dall'assassino di un noto horror adolescenziale con Neve Campbell. Tale assassino era ovviamente Chuck Norris.",
"Alle morbide Fruit Joy, Chuck Norris puo' resistere.",
"Anche Chuck Norris ha un cuore. E lo usa come portachiavi.",
"Anche il freddo trema davanti a Chuck Norris.",
"Berlusconi puo' unire la Sicilia all'Italia con un ponte.",
"Bisogna dare a Chuck Norris quel che e' di Cesare.",
"Chuck Norris a volte ti porge il dito indice e ti chiede simpaticamente di tirarlo. Appena lo tiri, ti arriva un calcio rotante sui denti. Poi Chuck scoreggia.",
"Chuck Norris ammazza il tempo con un calcio rotante.",
"Chuck Norris annega i pesci.",
"Chuck Norris apre le bottiglie di birra coi denti. Dei propri nemici.",
"Chuck Norris apre le matrioske dalla piu' piccola alla piu' grande.",
"Chuck Norris aveva previsto la nascita di Nostradamus.",
"Chuck Norris brucio' un'intera foresta durante alcuni esperimenti con l'acqua.",
"Chuck Norris conosce il nome di Mac Gyver.",
"Chuck Norris corre i 100 metri piani in -4 secondi.",
"Chuck Norris da ragazzino andava a suonare per scherzo i campanelli delle case. Gli abitanti se la davano a gambe di nascosto.",
"Chuck Norris detiene il record di punti in un'unica partita di basket: centosettanta. Distribuiti equamente tra gambe, braccia e volto degli avversari.",
"Chuck Norris deve usare una controfigura nelle scene di pianto.",
"Chuck Norris di notte gira con una pila, non perche' abbia paura del buio, ma perche' il buio ha paura di Chuck Norris.",
"Chuck Norris dorme con un cuscino sotto alla pistola.",
"Chuck Norris da' fuoco alle formiche con una lente di ingrandimento. Di notte.",
"Chuck Norris era inizialmente l'interprete di Palla di Lardo in Full Metal Jacket, ma e' stato sostituito quando si sono resi conto che era impossibile girare la scena del suicidio: le pallottole si fermavano nella barba.",
"Chuck Norris estrae cilindri dai conigli.",
"Chuck Norris fa bungee jumping senza elastico.",
"Chuck Norris fa gli origami con lastre di ghisa",
"Chuck Norris fa la christmas card ad agosto.",
"Chuck Norris fa pagare care le provocazioni gratuite.",
"Chuck Norris fa provincia.",
"Chuck Norris fa spesso tardi al lavoro. Non e' raro che la sveglia si rifiuti di suonare per paura di essere spenta a calci rotanti.",
"Chuck Norris fa una breve comparsata ne 'Il buono, il brutto e il cattivo'. E' il titolo.",
"Chuck Norris fuma toscani. Vivi.",
"Chuck Norris gioca a 'm'ama, non m'ama' con i rami di un baobab. Se esce 'non m'ama', fa ricrescere un ramo a calci rotanti e lo strappa. 'M'ama'.",
"Chuck Norris giocava con i New York Yankees. Il suo primo fuori campo durante un match casalingo e' stato raccolto da un tifoso felicissimo. Nello stadio dei Chicago Cubs.",
"Chuck Norris guarda la videocassetta di",
"Chuck Norris ha bandito gli arcobaleni dallo stato del North Dakota.",
"Chuck Norris ha brevettato la paura.",
"Chuck Norris ha comprato l'uomo da 6 milioni di dollari a meta' prezzo.",
"Chuck Norris ha contato fino ad infinito - due volte.",
"Chuck Norris ha costruito un transatlantico dentro una bottiglia di vetro in scala 1:1.",
"Chuck Norris ha costruito una macchina del tempo e l'ha usata per tornare  indietro in tempo per fermare l'assassinio di JFK. Come Oswald sparo',  Chuck riusci' a deviare la traiettoria dei tre proiettili con il solo uso  della barba. La testa di JFK pero' esplose comunque dallo stupore.",
"Chuck Norris ha creato un milione di posti di lavoro. Tutti becchini.",
"Chuck Norris ha fatto il giro del mondo in 80 giorni in un quarto d'ora.",
"Chuck Norris ha fatto il suo primo milione di dollari all'eta' di sei anni grazie alla fatina dei dentini. I denti che lasciava sotto il cuscino pero' non erano i suoi.",
"Chuck Norris ha fatto tredici al Superenalotto.",
"Chuck Norris ha giocato alla roulette russa con una pistola completamente carica e ha vinto.",
"Chuck Norris ha incastrato Roger Rabbit.",
"Chuck Norris ha inventato gli aerei perche' era stanco di essere l'unico in grado di volare.",
"Chuck Norris ha inventato la famosa ricetta segreta del Kentucky Fried Chicken, con undici erbe e spezie. Nessuno ha pero' mai nominato il dodicesimo ingrediente: la paura.",
"Chuck Norris ha investito un autotreno facendo jogging.",
"Chuck Norris ha la migliore faccia da poker di tutti i tempi. Questo lo ha aiutato a vincere il world series di poker nel 1983 nonostante avesse in mano un joker, un due di picche, un sette di quadri, un 4 verde di Uno e un biglietto 'esci gratis di prigione' del monopoli.",
"Chuck Norris ha la patente per guidare gli immobili.",
"Chuck Norris ha mangiato la testa di Ozzy Osbourne.",
"Chuck Norris ha ordinato un Big Mac da Burger King, e gliel'hanno dato.",
"Chuck Norris ha passato dieci anni chiuso in gabbia con una tigre in Vietnam. Non perche' fosse stato catturato dai vietcong, ma perche' aveva bisogno di trascorrere un po' di tempo da solo coi suoi pensieri.",
"Chuck Norris ha percorso tutto il campo di Holly e Benji. In un episodio.",
"Chuck Norris ha perso la verginita' prima di suo padre.",
"Chuck Norris ha risolto il mistero del Triangolo delle Bermuda col Teorema di Pitagora.",
"Chuck Norris ha risolto il problema della fame nel mondo sterminando l'intera specie umana.",
"Chuck Norris ha risolto il problema della fame nel mondo. Ovunque viaggi, si porta dietro un panino. A chi osa fargli notare che 'fame nel mondo' non era inteso in quel senso, Chuck Norris amputa le braccia semplicemente fissandole a lungo.",
"Chuck Norris ha rotto una catena di Sant'Antonio e gli ha fottuto la bici.",
"Chuck Norris ha salvato il presidente Bush, che stava soffocando per un salatino, semplicemente colpendolo con un calcio rotante alla gola. Chuck Norris non si era accorto che il presidente stava soffocando, voleva semplicemente colpirlo con un calcio rotante alla gola.",
"Chuck Norris ha scoperto l'acqua fredda.",
"Chuck Norris ha scritto tutte le parole del testo della sigla di 'Happy Days'... con la sua barba.",
"Chuck Norris ha soffocato le Geox.",
"Chuck Norris ha trovato Nemo.",
"Chuck Norris ha ucciso la mamma di Bambi con un calcio rotante.",
"Chuck Norris ha ucciso per molto meno.",
"Chuck Norris ha usato la Cosa dei Fantastici Quattro per ripiastrellarsi il  bagno.",
"Chuck Norris ha vinto il palio di Siena con il cavallo degli scacchi.",
"Chuck Norris ha vinto il premio Nobel per la letteratura con un SMS.",
"Chuck Norris ha vinto il prestigioso premio di 'coppia dell'anno' per la rivista GQ. Da solo.",
"Chuck Norris ha vinto la maratona di New York. Correndo a Boston.",
"Chuck Norris ha vinto la medaglia d'oro di bob a quattro alle Olimpiadi Invernali di Torino 2006. Da solo. Doppiando gli avversari.",
"Chuck Norris ha vinto una gara di assoli di pianoforte con un singolo accordo. Di ukulele.",
"Chuck Norris ha visitato tutti i pianeti del sistema solare. Si spiega cosi' l'assenza di forme di vita extraterrestre.",
"Chuck Norris interpreta la parte dello squalo ne 'Lo squalo' con una pinna attaccata alla schiena. Steven Spielberg pensava che, in questo modo, le reazioni di puro terrore degli attori sarebbero state piu' realistiche. Al termine delle riprese, comunque, Chuck Norris li mangio'.",
"Chuck Norris mangia i giocatolli dei transformer come veicoli e li caga trasformati in robot.",
"Chuck Norris mangia il brodo con la forchetta.",
"Chuck Norris mangia la fonduta con le mani.",
"Chuck Norris mangia la pizza con le mani. A volte ci mette anche le olive.",
"Chuck Norris muore ogni notte per darsi i numeri in sogno.",
"Chuck Norris non bagnava il letto da bambino. Il letto si bagnava da solo per la paura.",
"Chuck Norris non colpira' mai un uomo con gli occhiali. Lo colpira' con  un",
"Chuck Norris non crede in Dio. Dio crede in Chuck Norris.",
"Chuck Norris non deve fare il numero. Lui alza la",
"Chuck Norris non dorme. Aspetta.",
"Chuck Norris non fa male ad una mosca. Peccato che tu non sia una mosca.",
"Chuck Norris non gioca a bocce perche' e' uno sport che non ha abbastanza palle.",
"Chuck Norris non gioca a ping pong, gioca solo a 'ping': gli basta un colpo per vincere.",
"Chuck Norris non ha bisogno di una donna per procreare: da un suo brufolo e' nata la stirpe dei draghi.",
"Chuck Norris non ha i globuli bianchi come tutti gli altri esseri umani. Infatti, i suoi globuli bianchi sono attraversati da una striscia nera, in quanto cinture nere di karate. I globuli bianchi di Chuck Norris sconfiggono i virus a calci rotanti.",
"Chuck Norris non ha letto la bibbia. L'ha scritta.",
"Chuck Norris non ha mai avuto bisogno di controfigure, ma la sua barba spesso ha fatto da controfigura per l'attore che interpretava Chewbacca.",
"Chuck Norris non ha mai sputato nel piatto in cui mangia. Sputa nel piatto in cui mangiano gli altri.",
"Chuck Norris non ha mai vinto l'Oscar, perche' lui non recita. Mai.",
"Chuck Norris non ha preso bene il mancato inserimento del suo volto a Mount Rushmore. Il risultato si chiama Grand Canyon.",
"Chuck Norris non lancia la palla al cane. Chuck Norris lancia il cane.",
"Chuck Norris non manda lettere minatorie. Le lettere minatorie mandano Chuck Norris.",
"Chuck Norris non porta l'orologio. Decide lui che ora e'.",
"Chuck Norris non sbaglia mai una parola. Se sbaglia, cambiano il vocabolario.",
"Chuck Norris non scuoce mai la pasta. Per uno strano fenomeno considerato inspiegabile dagli studiosi, la temperatura dell'acqua nelle pentole di Chuck precipita a zero sempre al momento giusto. Tutto cio', comunque, non potra' mai essere verificato perche' Chuck Norris non cucina mai, mangia sempre tutto crudo. Anche la pasta.",
"Chuck Norris non segue la moda: la moda segue Chuck Norris. Poi lui si volta e la colpisce con un calcio rotante. Nessuno segue Chuck Norris. Nessuno.",
"Chuck Norris non si sveglia all'alba, e' il sole che sorge quando si sveglia Chuck Norris.",
"Chuck Norris non taglia l'erba. Semplicemente le ordina di non crescere. Guardandola.",
"Chuck Norris non va mai dal dentista perche' ha i denti in adamantio. I nemici di Chuck Norris non vanno dal dentista perche' non hanno denti.",
"Chuck Norris ogni tanto esplode. Questo avviene perche' i suoi atomi si prendono a calci rotanti tra di loro. Per paura di ritorsioni da parte di Chuck, una volta esplosi chiedono scusa e si ricompongono immediatamente.",
"Chuck Norris ogni weekend uccide 14 bianchi, solo per dimostrare che non e' razzista.",
"Chuck Norris puo' colpirti tanto forte da alterarti il DNA. Occasionalmente, dopo generazioni, i tuoi avi sentiranno una fitta in testa e si chiederanno 'ma che cazzo e' stato?'.",
"Chuck Norris puo' disegnare un triangolo con quattro lati.",
"Chuck Norris puo' dividere per zero.",
"Chuck Norris puo' essere visto ad occhio nudo dallo spazio.",
"Chuck Norris puo' far perdere la verginita' a voce.",
"Chuck Norris puo' giudicare Caterina Caselli",
"Chuck Norris puo' ricostruire un uovo sbattuto.",
"Chuck Norris puo' sbattere una porta girevole.",
"Chuck Norris puo' superare il tonno insuperabile. A destra.",
"Chuck Norris puo' vincere una partita di Forza4 facendo solo tre mosse.",
"Chuck Norris puo' volare. Questo perche' la forza di gravita' non ha il coraggio di dirgli che non puo'.",
"Chuck Norris quando ha prurito cerca una pianta di rovi e si butta dentro.",
"Chuck Norris raccoglie la propria adrenalina in eccesso in piccoli contenitori metallici, noti anche come pile stilo. E' stato stimato che, se non lo facesse, potrebbe sterminare un'intera nazione di 300.000 abitanti semplicemente digitando un punto esclamativo sulla tastiera del suo PC.",
"Chuck Norris ricava la tequila direttamente dall'agave, perche' l'agave  non osa contraddirlo.",
"Chuck Norris riesce a baciarsi la schiena.",
"Chuck Norris riesce a fare i castelli di carte con il mazzo del solitario di windows.",
"Chuck Norris riesce a paracadutarsi da 1000 metri con un sacchetto della spesa",
"Chuck Norris riesce a prendere al volo una freccia lanciata da un arco. Dopo averla tirata lui stesso.",
"Chuck Norris riesce ad aprire le porte del Generale Lee.",
"Chuck Norris rotola in salita.",
"Chuck Norris sa cosa hai fatto l'estate scorsa.",
"Chuck Norris sa se e' nato prima l'uovo o la gallina. E sa anche chi e' morto per primo. E come. Con un calcio rotante, ovviamente.",
"Chuck Norris salta i fossi per lungo.",
"Chuck Norris si collega in wireless con il Commodore 64.",
"Chuck Norris si diverte a distruggere i castelli di sabbia dei bambini a calci rotanti. La causa di questo suo comportamento e' da imputarsi alla sbadataggine di un moccioso che e' inciampato sul Colosseo in scala 1 a 1 costruito da Chuck Norris in una spiaggia del Mar Bianco, ribattezzato in seguito Mar Rosso. Non pago, Chuck Norris volo' a Roma, dove con una raffica di calci rotanti devasto' parte del Colosseo originale, con l'ordine preciso di non ripararlo mai piu'.",
"Chuck Norris si trovava sul set del Corvo durante una delle sue innumerevoli partite alla roulette russa con la pistola completamente carica. Dopo essersi sparato cinque colpi nella barba, annoiato, ha abbandonato su un tavolo la pistola con l'ultimo colpo in canna. Le conseguenze di questo gesto le conosciamo tutti.",
"Chuck Norris si e' suicidato con un calcio rotante per aver detto: 'Io sono Chuck Norris!'.",
"Chuck Norris sta parlando con Travis in Taxi Driver.",
"Chuck Norris suona il postino sempre due volte",
"Chuck Norris taglia i grissini col tonno.",
"Chuck Norris ti frega sempre con il gioco delle tre scatolette. Solo che lui ne usa una sola.",
"Chuck Norris un giorno aveva scommesso con la NASA che avrebbe potuto sopravvivere ad un rientro dallo spazio senza indossare la tuta da astronauta. Il 19 Luglio 1999, un Chuck Norris completamente nudo rientro' nell'atmosfera terrestre tuffandosi da una navicella raggiungendo la temperatura di tremila gradi centigradi e spazzando via 10 stati americani nell'impatto al suolo. Un'imbarazzatissima NASA affermo' in pubblico' che si era trattato di un meteorite, e deve ancora una birra a Chuck Norris.",
"Chuck Norris un giorno colpi' Bruce Lee con un calcio rotante, spezzandolo in due. Il risultato furono Jet Li e Jackie Chan.",
"Chuck Norris un giorno ha creato un lanciafiamme urinando in un accendino.",
"Chuck Norris un giorno ha pensato che fosse utile imbottigliare la propria urina. Da allora e' conosciuta come Red Bull.",
"Chuck Norris un giorno ha trovato un bigliettino con la frase 'Chuck Norris ha contato fino ad infinito. Due volte' in un Bacio Perugina.",
"Chuck Norris un giorno ha vinto la Champions League giocando da solo, senza mai usare ne' i piedi ne' la testa, semplicemente fissando negli occhi gli avversari, che terrorizzati iniziavano a segnare nella propria porta. Il solo Gennaro Gattuso, allora biondo e aitante trequartista dai piedi buoni, oso' provare a tenergli testa.",
"Chuck Norris una volta ha calciato un cavallo sul mento. Ora i suoi discendenti sono noti come 'giraffe'.",
"Chuck Norris una volta ha mangiato tre bistecche da 2 chili in un'ora. Ha passato i primi 45 minuti scopando con la cameriera.",
"Chuck Norris una volta ha mangiato una torta intera prima che i suoi amici potessero dirgli che all'interno c'era una spogliarellista.",
"Chuck Norris una volta ha sbattuto accidentalmente contro una torre. A Pisa.",
"Chuck Norris una volta ha trovato la lampada del Genio. L'ha strofinata, e ha concesso al Genio due desideri. Come primo desiderio il Genio ha chiesto di poter vivere. Come secondo desiderio ha chiesto un bicchiere di vino. Chuck Norris l'ha decapitato con un calcio rotante. Perche' Chuck Norris dice 'no' all'alcool. E non esaudisce nessun desiderio. Mai.",
"Chuck Norris una volta ha trovato lavoro in un lunapark. Era il calcinculo.",
"Chuck Norris una volta ha ucciso 182 persone con 6 proiettili.",
"Chuck Norris una volta s'e' scopato un buco nero, solo per dimostrare che ce l'aveva abbastanza lungo.",
"Chuck Norris una volta e' accidentalmente inciampato e ha distrutto l'intero stato dell'Ohio.",
"Chuck Norris usa un serpente a sonagli come preservativo.",
"Chuck Norris vende regolarmente la pelle dell'orso senza averlo ancora preso. Una formalita'. Si puo' acquistare usando l'opzione 'pre-order now'.",
"Chuck Norris vince a Risiko usando un solo carro armato. Non pago, attacca anche tutti i carri armati rimasti nella scatola. E conquista anche la scatola.",
"Chuck Norris vince una gara di stile libero nuotando a rana.",
"Chuck Norris vinse una gara di tiro al piattello sparando cazzate.",
"Chuck Norris e' apparso alla Madonna",
"Chuck Norris e' bravissimo a suonare la batteria con un braccio solo. Quello del batterista dei Def Leppard.",
"Chuck Norris e' campione del mondo in carica di salto con l'asta. Quando gli e' stato fatto notare che aveva saltato senza asta, si e' abbassato i pantaloni. E ha ovviamente decapitato con un calcio rotante l'avventato interlocutore.",
"Chuck Norris e' contrario alla prostituzione. Se fosse favorevole, tutte le donne sarebbero sulla strada.",
"Chuck Norris e' il motivo per cui la Gioconda sorride.",
"Chuck Norris e' immune al freddo. Un giorno ha salvato una comitiva di escursionisti svizzeri travolta da una slavina semplicemente immergendosi nella neve. Nudo. Poi li ha comunque uccisi a furia di calci rotanti in pancia, che non si pensi che improvvisamente e' diventato un fottuto Superman del cazzo.",
"Chuck Norris e' in grado di cambiarvi una banconota da cento euro in monetine da un euro semplicemente colpendola con un calcio rotante.",
"Chuck Norris e' in grado di costruire una mongolfiera facendo palloni con un bigbabol. Uno solo.",
"Chuck Norris e' in grado di scalare le montagne in bicicletta. Su una ruota sola. Senza mani.",
"Chuck Norris e' l'unico al mondo in grado di far fare il sorriso ai Sofficini con la forchetta come nella pubblicita'.",
"Chuck Norris e' nato prima sia dell'uovo che della gallina.",
"Chuck Norris e' particolarmente consigliato nelle diete povere di calcio.",
"Chuck Norris e' rimasto coinvolto in uno scontro frontale con un bus ed e' miracolosamente sopravvissuto. Stava attraversando la strada.",
"Chuck Norris e' sempre circondato da montagne di donne. Morte. Ammazzate. Da calcio rotante.",
"Chuck Norris e' stato campione mondiale di Formula Uno. Senza macchina.",
"Chuck Norris e' stato capace di vincere una partita a scacchi anche dopo che gli avevano mangiato il re.",
"Chuck Norris e' vegetariano. Nel senso che prima di mangiare un animale, lo riduce in stato vegetativo.",
"Chuck Norris e' venuto al mondo uscendo dallo stomaco di Alien.",
"Chuck Norris, a Hattrick, allena calci piazzati.",
"Chuck Norris, ancora teenager, ha messo incinta ogni singola suora di un convento nascosto sulle colline della Toscana. Nove mesi dopo le suore hanno dato alla luce i Miami Dolphins del 1972, l'unica squadra imbattuta nella storia del football professionistico.",
"Chuck Norris, dopo aver letto ottomila segnalazioni via e-mail riguardanti la montagna di Maometto, si e' rotto i coglioni e ha eliminato per sempre la fottuta montagna con un unico, monumentale calcio rotante, sbriciolandola all'istante e promettendo di fare lo stesso con tutti coloro che avessero spedito nuovi facts sull'argomento in questione.",
"Chuck Norris, prima di volere una cosa, la ottiene.",
"Chuck Norris, quando gioca a scacchi, vince sempre . Con la prima mossa.",
"Chuck Norris, quando mangia il Duplo, fa nello stesso momento l'approccio dentale e labbiale.",
"Chuck Norris: se non lo conosci lo eviti, se lo conosci ti uccide.",
"Chunk Norris dice 'no' alla caccia, anche perche' gli animali vanno spontaneamente a bussare alla sua porta e si sparano da soli.",
"Ci sono 100 probabilita' su 100 che Chuck Norris sia tuo padre.",
"Ci sono 31 lettere nell'alfabeto anglosassone. Tuttavia, solo Chuck Norris conosce le 5 lettere segrete.",
"Ci sono solo due tipi di persone al mondo: gli sfigati, e Chuck Norris.",
"Ci sono solo quattro cavalieri dell'Apocalisse, perche' Chuck Norris preferisce andare a piedi.",
"Contrariamente a quanto si crede, il vero nome di Chuck Norris e' Chuck Morris. Purtroppo, una stanghetta della M e' stata inavvertitamente amputata da un calcio rotante eseguito da Chuck all'anagrafe.",
"Da una costola di Adamo nacque Eva. Da una costola di Chuck Norris nacque Wonder Woman.",
"Da una decina d'anni Chuck Norris, come secondo lavoro, fa il kamikaze.",
"Dato che 'Una mela al giorno toglie il medico di torno', Chuck Norris ha pensato bene di mangiarsi New York per levarsi i medici dai maroni per tutta la vita.<span style='font-size:78%;'>",
"Deckard, in Blade Runner, disse: 'Ho visto cose che voi umani non potreste immaginare'. Aveva visto Chuck Norris.",
"Deep Blue ha battuto il campione mondiale di scacchi Garry Kasparov. Dopodiche`  ha osato sfidare Chuck Norris. Ora Deep Blue gestisce con gioia riconoscente  l'intermittenza delle lucine dell'albero di Natale di Chuck Norris.",
"Dietro ad ogni uomo di successo c'e' una donna.",
"Dio aveva chiesto dieci giorni per creare il mondo. Chuck Norris gliene ha dati sei.",
"Dio ha una foto abbracciato a Chuck Norris. Autografata.",
"Dopo aver saputo che Chuck Norris lo stava aspettando, Godot e' arrivato. Ed e' stato ucciso con un calcio rotante.",
"Durante l'ultima cena, Chuck Norris ha spezzato il pane. E il tavolo. E tutti i commensali.",
"Durante l'ultimo All-star game di NBA, Chuck Norris ha vinto la gara  delle schiacciate schiacciando la testa a un giurato con il pollice e  l'indice e facendola esplodere.",
"Durante l'ultimo Celebrity Deathmatch Chuck Norris ha battuto Dio.",
"Durante la Seconda Guerra Mondiale, Chuck Norris abbatte' un aereo tedesco con un  dito semplicemente gridando Bang!",
"Durante lo scorso Halloween, un gruppo di bambini hanno suonato alla porta di casa Norris. Alla domanda 'Dolcetto o scherzetto?', Chuck Norris ha staccato una gamba ad uno dei bambini, l'ha caramellata col suo stesso sangue e ha risposto 'dolcetto'.",
"Durante un allenamento con Wolverine, Chuck Norris ha accidentalmente perso il suo testicolo sinistro, conosciuto ora da tutti con il suo vero nome: Giove.",
"Durante un concerto dei Pooh, Chuck Norris ha fermato la musica.",
"Durante un rodeo, Chuck Norris ha disarcionato un toro che tentava di tenerlo a bada.",
"Durante una partita di calcio Chuck Norris venne atterrato. L'arbitro concesse una punizione. Chuck Norris decapito' l'avversario con un calcio rotante. Era la migliore punizione per quel bastardo.",
"Durante una sua partecipazione a 'Chi vuol essere milionario VIP', Chuck Norris ha detto 'io' e ha vinto.",
"Errare e' umano, perseverare e' diabolico, uccidere e' Chuck Norris.",
"Esiste un reality show sulla vita di alcuni dei figli di Chuck Norris. Si intitola Power Rangers.",
"Fonzie con un pugno riusciva a far partire il Juke-box. Chuck Norris con un pugno fa partire i concerti a San Siro.",
"Freddy Krueger non dorme mai per paura di sognare Chuck Norris.",
"Gesu' puo' camminare sulle acque. Chuck Norris puo' camminare su Gesu'.",
"Gesu' una volta ha moltiplicato i pani e i pesci. Chuck Norris ha diviso i pani, aggiunto i pesci, sottratto le lische e inventato il tramezzino al salmone.",
"Gli essere umani sono fatti da un 75% di acqua. L'acqua e' formata da un 75% di Chuck Norris.",
"Ho il sospetto che certi commenti anonimi li scriva D a M e poi M a D per pareggiare i conti. A Chuck Norris nessuno scrive niente. Dire a Chuck Norris che e' un figo implicherebbe l'ipotesi che possa non esserlo. Nessuno fa apprezzamenti su Chuck Norris. Nessuno.",
"I buchi neri sono dovuti a Chuck Norris che prende a calci rotanti l'universo.",
"I cerchi sui campi di grano sono il modo di Chuck Norris di comunicare al mondo che a volte il fottuto grano deve starsene giu'.",
"I comunisti in realta' non mangiano i bambini, perche' se li mangia prima Chuck Norris. I comunisti. E anche i bambini.",
"I fermenti lattici degli yogurt di Chuck Norris sono tutti morti.",
"I proiettili indossano il giubbotto anti-Chuck Norris.",
"I rubinetti in casa di Chuck Norris non perdono, vincono.",
"I testicoli di Chuck Norris non producono spermatozoi, producono tanti piccoli ninja con in mente un solo obiettivo: distruggere.",
"Il 26 dicembre 2004 Chuck Norris ha fatto il suo primo tuffo nel Pacifico.",
"Il 29 maggio del 1953 Edmund Hillary e lo sherpa Tensing raggiunsero la vetta dell'Everest, dove li stava aspettando Chuck Norris che beveva una birra. Ghiacciata.",
"Il Mar Morto e' stato ucciso da Chuck Norris.",
"Il Santo Graal e' a casa di Chuck Norris. Lo usa per tenerci lo spazzolino da denti.",
"Il bambino del Sesto Senso inizialmente doveva essere interpretato da Chuck Norris. C'era solo un problema: Chuck Norris non vede la gente morta. La gente morta pero' ha sicuramente visto Chuck Norris.",
"Il cavallo bianco di Chuck Norris e' nero.",
"Il cavallo dei pantaloni di Chuck Norris e' Furia.",
"Il detto 'vedi Parigi e poi muori' e' nato durante un breve ma intenso periodo di soggiorno di Chuck Norris nella capitale francese.",
"Il diluvio universale fu un estremo tentativo di Dio di liberarsi di Chuck Norris. Chuck Norris, fortunatamente, la prese con sportivita' e si fece una risata. Altrimenti non saremmo qui a raccontarlo.",
"Il film 'King Kong' originariamente avrebbe dovuto chiamarsi 'Chuck Norris'. Per calarsi nella parte, Chuck Norris ha trattenuto il respiro facendo pressione su se' stesso, diventando in questo modo cinque volte piu' grande ed espellendo peli da tutto il corpo fino a coprirsi interamente. Il progetto, purtroppo, e' saltato quando il regista gli ha fatto notare che uno scimmione non dovrebbe indossare il cappello da Walker Texas Ranger e Chuck, adirato, lo ha scaraventato sul set de Il mago di OZ con un calcio rotante. Nel tornare normale, Chuck Norris ha raccolto tutta la peluria in eccesso e ha fondato la Woolrich. Il King Kong utilizzato nella pellicola definitiva e' Steven Seagal.",
"Il film 'Una settimana da dio' era inizalmente intitolato 'Una settimana da Chuck Norris'. La trama prevedeva che Chuck Norris apparisse a Jim Carrey e gli regalasse i suoi poteri per una settimana. Il progetto e' sfumato perche' Chuck Norris ha interpretato la frase 'regalare i poteri' come 'colpire con un calcio rotante sulla nuca'.",
"Il gioco 'Cluedo - Chuck Norris Edition' e' stato ritirato dal mercato perche' la soluzione di tutti gli enigmi era sempre la stessa: Chuck Norris, con un calcio rotante, in biblioteca.",
"Il gioco degli scacchi, originariamente, prevedeva tanti Chuck Norris in miniatura al posto dei pedoni. Vennero sostituiti quando ci si accorse che, di loro spontanea iniziativa, prendevano a calci rotanti tutte le altre pedine rovinando le partite.",
"Il governo degli Stati Uniti spende 40 miliardi di dollari all'anno in prevenzione di calamita' naturali. Di questi, 35 miliardi sono spesi per garantire che la birra di Chuck Norris sia sempre fredda.",
"Il perito chimico si illude di sapere: legge CN e pensa al cianuro.",
"Il plasma del televisore di Chuck Norris e' quello del sangue delle sue vittime.",
"Il presidente Roosevelt proclamo': 'L'unica cosa di cui dobbiamo avere paura e' la paura stessa. E Chuck Norris'.",
"Il prete di 'Non ci resta che piangere' deve pagare ogni anno centinaia di  migliaia di dollari di diritti d'autore a Chuck Norris per la frase 'ricordati  che devi morire'",
"Il primissimo CSI avrebbe dovuto essere intitolato",
"Il primo a dividere l'atomo non e' stato Einstein. E' stato Chuck Norris: l'ha  frantumato con un solo calcio rotante.",
"Il primo nome scelto da Ratzinger era Chuck Norris II. A Chuck Norris non e' piaciuto l'accostamento con 'II'. Chuck Norris non e' secondo a nessuno. Ha detto 'no' con un calcio rotante e Ratzinger ha annuito mestamente, rotolando giu' dal sagrato di San Pietro.",
"Il segnale con l'uomo in carrozzella non indica che un parcheggio sia riservato ai disabili, ma che appartiene di diritto a Chuck Norris, e che verrai ridotto su una sedia a rotelle se oserai parcheggiarci sopra.",
"Il terzo segreto di Fatima non e' la rivelazione dell'attentato al Papa, come molti ingenui sono soliti credere, ma il PIN del telefono cellulare di Chuck Norris. A chi obietta che all'epoca delle rivelazioni i cellulari non esistessero, Chuck Norris e' solito spezzare un femore.",
"Il titolo originale di 'Alien vs Predator' era 'Alien e Predator vs Chuck Norris'. Il film e' stato cancellato subito dopo essere entrato in preproduzione. Nessuno avrebbe pagato nove dollari per vedere un film che durava 14 secondi.",
"Il triangolo delle Bermuda era una volta noto come il quadrato delle Bermuda, fino a quando Chuck Norris con un calcio rotante non ha distrutto uno degli angoli.",
"Il videogioco 'Super Mario Bros' e' liberamente ispirato ad una giornata tipo di Chuck Norris, che e' solito vagare per le citta' saltando in testa alla gente e lanciando loro gusci giganti di tartaruga. Misteriosamente omessa la parte in cui la prende a calci rotanti.",
"In tutti i thriller, gialli e horror usciti al cinema dal 1973 ad oggi l'assassino e' Chuck Norris.",
"In una comunissima stanza ci sono 1257 oggetti con i quali Chuck Norris potrebbe ucciderti, compresa la stanza stessa.",
"In una conversazione, e' sempre Chuck Norris a rompere il ghiaccio. E lo fa con un calcio rotante.",
"In una rara scena tagliata de 'L'Impero colpisce ancora', Chuck Norris rivela a Darth Vader di essere suo padre.",
"Jimi Hendrix suonava con i denti. Anche Chuck Norris ora suona con i denti. Di Jimi Hendrix.",
"L'erba del vicino di Chuck Norris e' meno verde della sua.",
"L'espressione 'Ciak, si gira' e' un omaggio del mondo del cinema al calcio rotante di Chuck Norris. Arrabbiato per la storpiatura del nome, Chuck Norris ha spezzato la clavicola al mondo del cinema con un calcio rotante.",
"L'uomo medio dopo aver fatto sesso si fuma una sigaretta. Chuck Norris dopo essersi fumato una sigaretta fa sesso. Sempre. Dappertutto. Con la prima persona che gli capita sotto tiro.",
"L'urlo di Chuck Norris terrorizza anche Chen.",
"La Luna non ruota attorno alla Terra, ruota attorno a Chuck Norris.",
"La Ricciarelli e' in grado di rompere un bicchiere di cristallo con un  acuto della Traviata. Chuck Norris e' in grado di rompere la Ricciarelli con  un bicchiere di cristallo. Cantando un ritornello degli Wham.",
"La gente monta e smonta a piacimento i mobili dell'IKEA. Chuck Norris monta e smonta a piacimento l'IKEA. E la gente che va all'IKEA.",
"La luce impiega circa 8 minuti per compiere il tragitto Sole-Terra. Chuck Norris ce ne impiega 2 fermandosi pure all'autogrill.",
"La massa corporea di un uomo e' composta al 70% da acqua. La massa corporea di Chuck Norris e' composta al 70% dal suo cazzo. La massa corporea dei suoi nemici e' scomposta.",
"La password di Chuck Norris e' 'chucknorris'. Dappertutto. E' di dominio pubblico. E nessuno ha ancora avuto il coraggio di usarla.",
"La prima legge della dinamica di Chuck Norris stabilisce che ad ogni sua azione non corrisponde alcuna reazione, o son cazzi.",
"La prima parola pronunciata da Chuck Norris, da piccolo, e' stata 'Chuck'. La seconda 'Norris'. La terza non c'e' mai stata. Da quel giorno, Chuck Norris si esprime a calci rotanti.",
"La prima stesura del Signore degli Anelli aveva Chuck Norris al posto di Frodo Baggins. Erano cinque pagine in tutto, perche' Chuck Norris prendeva a calci rotanti nel culo Sauron a meta' del primo capitolo.",
"La prima stesura della sceneggiatura di Fight Club prevedeva Chuck Norris in tutti i ruoli. Tutti.",
"La principale causa scatenante degli incendi nelle foreste non e' la siccita', ma Chuck Norris che vi festeggia il suo compleanno usando le molotov al posto delle candeline.",
"La seconda legge della dinamica di Chuck Norris stabilisce che ad ogni azione altrui corrisponde una sua reazione uguale e contraria, dove per contraria si intende 'con la faccia corrucciata' e per uguale 'un milione di volte piu' potente'. Solitamente, la reazione si manifesta sottoforma di calci rotanti.",
"La stesura originale della Divina Commedia, prevedeva che nell'inferno la pena fosse uguale per tutti: sarebbero stati presi a calci rotanti in eterno da Chuck Norris. Dante cambio' idea non tanto per la monotonia, quanto perche' terrorizzato dalla sola idea di raccontare simili vicende.",
"La tastiera di Chuck Norris non ha il punto di domanda. Chuck Norris non deve chiedere. Mai.",
"La versione originale di 'Apocalypse Now' doveva essere un solo lungo primo piano di Chuck Norris. Temendo conseguenze legali per morti da infarto tra il pubblico, la produzione abbandono' il progetto.",
"Le avventure delle Tartarughe Ninja sono basate su una storia vera: Chuck Norris una volta inghiotti' quattro tartarughe e quando le cago' erano alte due metri e conoscevano le arti marziali.",
"Le ciambelle di Chuck Norris vengono sempre con il buco. Sempre.",
"Le lacrime di Chuck Norris curano il cancro. Purtroppo non ha mai pianto. Mai.",
"Le mezze stagioni non esistono piu' perché a Chuck Norris non piace lasciare le cose a meta'.",
"Le parole 'pieta'', 'compassione' e 'pena' sono state eliminate a sberle dal vocabolario di Chuck Norris, che le riteneva un inutile spreco di spazio quando potevano comodamente essere riassunte in 'non morte'.",
"Le rockstar muoiono spesso giovani perche' Chuck Norris cambia gusti molto facilmente.",
"Le saghe di 'Rambo' e 'Rocky' originariamente erano una cosa sola, chiamata 'Chuck Norris', in cui lui diventava campione dei pesi massimi con una gamba e con l'altra liberava prigionieri in Vietnam.",
"Lo Chef Tony ha provato ad affettare Chuck Norris con la lama taglia tutto della serie Miracle Blade 3 - serie perfetta. Non ce l'ha fatta. Ora pezzi dello Chef Tony sono nella buca degli avanzi in cui finivano i filetti di pomodori e il residuo di scarpone.",
"Maradona palleggia con le arance, Chuck Norris palleggia con Maradona che palleggia con le arance.",
"McGyver puo' costruire un aereo con una gomma da masticare e delle graffette, ma Chuck Norris puo' spiaccicargli la testa contro un muro con un calcio rotante e portarglielo via.",
"Mio cuggino conosce un colpo segreto che se te lo da' dopo tre giorni muori. Gliel'ha insegnato Chuck Norris.",
"Ne 'I promessi sposi', l'Innominato e' ovviamente Chuck Norris.",
"Ne uccide piu' la penna della spada. Chuck Norris uccide piu' della penna.",
"Nei due film sugli X-men non sono stati usati effetti speciali. Molto semplicemente Chuck Norris era la controfigura di tutti i personaggi.",
"Nei mondiali di Usa '94 e' stata introdotta la regola della 'sudden death' in ottemperanza al concetto di 'calcio' di Chuk Norris.",
"Neil Armstrong, appena arrivato sulla Luna, ha trovato un post-it con scritto 'Chuck Norris was here'.",
"Nel 1970 Chuck Norris e' stato fotografato dallo yeti.",
"Nel Vangelo secondo Chuck Norris, Dio ha un ruolo di secondo piano. E di Gesu' non c'e' traccia.",
"Nel copione originale di 'Point Break', era previsto che i rapinatori indossassero una maschera di Chuck Norris al posto di quelle dei presidenti americani. Ci si accorse subito, pero', che in questo modo tutte le rapine sarebbero filate via lisce e senza complicazioni, rendendo poco emozionante il film.",
"Nel film 'E.T.', la famosa scena della bicicletta che vola illuminata dalla luna non e' stata creata con un effetto speciale. La bicicletta e' stata infatti lanciata in orbita da Chuck Norris con un calcio rotante, senza motivo apparente. La scena piacque molto alla produzione, che decise di tenerla. Tuttavia, il bambino precipito' e mori', e per farsi perdonare Chuck Norris porto' a termine le riprese del film al suo posto. La felpa rossa col cappuccio lo rendeva irriconoscibile.",
"Nella Bibbia, Gesu' ha trasformato l'acqua in vino, ma poi Chuck Norris ha trasformato quel vino in birra.",
"Nella tradizionale corsa dei tori di Pamplona, non sono i tori ad inseguire le persone, e' l'idea che un giorno Chuck Norris possa venire a Pamplona a far scappare i tori E le persone. In realta' Chuck Norris non ha mai messo piede a Pamplona e forse mai lo fara', cosa che rende questo fenomeno ancora piu' inspiegabile.",
"Nella vita di un bambino, il vero trauma non e' tanto scoprire che Babbo Natale non esiste, quanto scoprire che Chuck Norris esiste.",
"Nessuno sa da chi sia partita l'idea dei facts. Questo perche' Chuck Norris sta provvedendo personalmente ad uccidere uno ad uno tutti coloro che hanno contrib",
"Nessuno e' perfetto. Quando Chuck lo venne a sapere, cerco' Nessuno, lo guardo' e lo disintegro' con un calcio rotante. Solo Chuck Norris e' perfetto.",
"Non Aprite Quella Porta. Dietro c'e' Chuck Norris.",
"Non ci sono armi di distruzione di massa in Iraq: Chuck Norris vive in Oklahoma.",
"Non esiste nessuna teoria dell'evoluzione. Esistono solo le specie alle quali Chuck Norris permette di vivere.",
"Ogni cinque secondi, in Africa, un bambino muore per colpa di un calcio rotante di Chuck Norris.",
"Ogni mattina in Africa quando sorge il sole un gazzella si sveglia ed inizia a correre per non essere mangiata da un leone. La stessa mattina in Africa quando sorge il sole un leone si sveglia ed inizia a correre per non essere mangiato da Chuck Norris.",
"Ogni pelo di barba di Chuck Norris ha a sua volta la barba.",
"Ogni volta che Chuck Norris sente nominare la frase 'La 'vergine'",
"Ogni volta che nell'universo viene commesso un crimine violento, Chuck Norris prende soldi dalla SIAE.",
"Originariamente la copertina di Sgt Pepper conteneva solo Chuck Norris, che impersonava tutti i personaggi. Poi l'hanno cambiata, ma il disco e' tutto opera sua.",
"Ozzy Osbourne stacca la testa dei pipistrelli a morsi. Chuck Norris stacca quella delle tigri siberiane.",
"Per arredare il suo salotto Chuck Norris ci ha messo l'acquario. Di Genova.",
"Per diventare famoso, il diavolo ha venduto l'anima a Chuck Norris",
"Per molti anni e' girata per il mondo la leggenda che Chuck Norris fosse malato di AIDS, a causa dell' alone fosforescente che lo circonda. L'alone in realta' altro non e' che la sua rabbia, talmente impetuosa da aver ormai raggiunto lo stato gassoso. Giusto per chiarire le cose, Chuck Norris ha comunque decapitato a calci rotanti chi ha messo in giro la diceria.",
"Per un punto passano infinite rette, ma un solo Chuck Norris. E se in quel momento Chuck Norris ha i coglioni girati, non ci saranno piu' ne' punti ne' rette.",
"Peter Parker e' diventato Spiderman dopo esser stato morso da un ragno radioattivo. Il ragno radioattivo era stato morso da Chuck Norris.",
"Prima di andare a letto Boogeyman, l'Uomo Nero, controlla sempre che non ci sia Chuck Norris nell'armadio.",
"Prima di pestare qualcuno, Jean-Claude Van Damme conta fino a 10. Prima di contare fino a 10, Chuck Norris pesta qualcuno.",
"Quando Chuck Norris bestemmia, Dio compie delle metamorfosi per non  contraddirlo.",
"Quando Chuck Norris butta i rifiuti, la carta e il vetro si separano da soli.",
"Quando Chuck Norris dorme il tempo si ferma, per paura di svegliarlo. Tutto cio' da l'illusione che Chuck Norris non dorma mai.",
"Quando Chuck Norris fa l'occhiolino, le ragazze si sciolgono. Letteralmente.",
"Quando Chuck Norris fa le flessioni, non alza se' stesso, abbassa la Terra.",
"Quando Chuck Norris fa una battuta, automaticamente si sentono delle risate preregistrate provenire fuori dal nulla.",
"Quando Chuck Norris fissa il sole, e' il sole a distogliere lo sguardo per primo.",
"Quando Chuck Norris gioca a Monopoli, influenza l'andamento dell'economia mondiale.",
"Quando Chuck Norris gioca a squash, il muro perde sempre.",
"Quando Chuck Norris ha fame, mangia un fungo atomico.",
"Quando Chuck Norris ha lasciato le sue impronte delle mani e dei piedi sulla Hollywood Walk of Fame, il cemento era asciutto.",
"Quando Chuck Norris lavorava al circo, veniva domato dai leoni. In due anni di spettacoli, ne sono morti 32 e 45 si sono licenziati. Ne mancano all'appello due: gira voce che Chuck li usi come pantofole da salotto. Vivi.",
"Quando Chuck Norris nacque ci furono ben 70 Re Magi che andarono a portargli in dono donne, sigari e fuoristrada.",
"Quando Chuck Norris parla, tutti ascoltano. E muoiono.",
"Quando Chuck Norris spedisce il suo modulo per il pagamento delle tasse, manda solo una foto di se' stesso, accovacciato e pronto ad uccidere. Chuck Norris, ad oggi, non ha mai dovuto pagare le tasse.",
"Quando Chuck Norris taglia la cipolla, piove.",
"Quando Chuck Norris ti sta per uccidere, non rivedi la tua vita. Rivedi tutte le puntate di Walker Texas Ranger.",
"Quando Chuck Norris vuole qualcosa di dolce, si mangia Ambrogio.",
"Quando Chuck Norris e' nato, aveva gia' fatto sesso. Tre volte.",
"Quando Dio disse 'sia fatta la luce', Chuck Norris disse 'chiedi per piacere'.",
"Quando KenShiro incontro' Chuck Norris gli diede un cazzotto sotto il mento e gli disse 'tu sei gia' morto'. Purtroppo non si era accorto che i peli della barba di Chuck Norris gli avevano bloccato la mano e premuto tutti i suoi punti di pressione. KenShiro esplose in mille pezzi.",
"Quando al termine del primo Terminator Arnold Schwarznegger dice 'tornero'', intende dire che sta andando a chiedere aiuto a Chuck Norris.",
"Quando era bambino Chuck Norris ha ricevuto come regalo un martello giocattolo, e ha donato al mondo Stonehenge.",
"Quando gli servono una banana flambe', Chuck Norris mangia prima il fuoco.",
"Quando hai la sensazione di essere osservato, ti sta guardando Chuck Norris.",
"Quando il saggio indica la luna, lo stolto guarda il dito, mentre Chuck Norris guarda il suo collo e si appresta  a spezzarglielo con un calcio rotante. Nessuno indica un cazzo di niente a Chuck  Norris, sa gia' lui dove guardare.",
"Quando la domenica Chuck Norris riceve la comunione durante la messa, al posto dell'ostia pretende un doppio cheesburger fumante.",
"Quando ordina un happy meal da McDonald's, Chuck Norris mangia prima il giocattolo.",
"Quando passa Chuck Norris, i girasoli non sanno piu' dove cazzo guardare ed esplodono.",
"Quando scatti una foto a Chuck Norris, il flash rimane accecato.",
"Quando stai morendo faresti bene a non andare verso la luce bianca in fondo al tunnel, perche' li' c'e' Chuck Norris che t'aspetta.",
"Quando un uomo col fucile e uno con la pistola incontrano Chuck Norris, sono matematicamente morti entrambi.",
"Quando e' imbottigliato nel traffico, Chuck Norris prende sempre la corsia piu'  veloce, e Murphy non ha proprio un cazzo da obiettare.",
"Robert Johnson ha venduto l'anima al diavolo in cambio del blues. Il diavolo era Chuck Norris e ha scambiato l'anima di Robert Johnson con un hamburger.",
"Ronaldinho prende quattro traverse di fila con un pallone. Chuck Norris prende quattro traverse di fila con Ronaldinho.",
"Se Bruce Banner perde il controllo si trasforma nell'incredibile Hulk. Se l'incredibile Hulk perde il controllo si trasforma in Chuck Norris.",
"Se Chuck Norris indossa un paracadute al rovescio e fa un salto da terra, e' in grado di arrivare a 4500 metri in pochi secondi",
"Se Chuck Norris parte per una vacanza ai tropici e sbaglia aereo ritrovandosi al Polo Nord , gli orsi polari pitturano il ghiaccio di giallo e si mettono il costume",
"Se Chuck Norris scrive su questo blog la battuta di Maometto e la montagna,  viene subito pubblicato e riceve un milione di commenti entusiasti",
"Se Chuck Norris si sveglia con la luna storta, la raddrizza a calci rotanti.",
"Se a Chuck Norris cade una fetta di pane con la marmellata, sicuramente gli cade con la marmellata rivolta in alto.",
"Se cercate 'Chuck Norris' su google, non otterrete risultati. Questo perche' Google sa che non siete voi a cercare Chuck Norris, ma e' lui a cercare - e trovare - voi, quando, dove e come vuole.",
"Se in una foresta cade un albero e non c'e' nessuno ad ascoltare, Chuck Norris potra' sentirne il rumore. Perche' e' stato lui ad abbatterlo, a calci rotanti.",
"Se la fate a Chuck Norris, aspettatevela sotto forma di calcio rotante.",
"Se mia nonna avesse le ruote, sarebbe una cariola. Se Chuck Norris avesse le ruote, sarebbe la batmobile.",
"Se pronunciate la combinazione di parole 'il punto debole di Chuck Norris e'...', vi arriva un calcio rotante dal nulla, tanto per chiarire.",
"Se stai leggendo queste parole, Chuck Norris ti ha fatto un grande favore: ha deciso di non ucciderti. Non ancora.",
"Se un battito d'ala di farfalla in Brasile puo' scatenare un tornado in Oklahoma, un calcio rotante di Chuck Norris in Oklahoma spiega facilmente il Big Bang.",
"Secondo Lavoisier, 'nulla si crea e nulla si distrugge'. Secondo Chuck Norris, Lavoisier dice un sacco di cazzate.",
"Secondo il Time Chuck Norris e' l'uomo dell'anno. Ogni anno.",
"Secondo quanto raccontato dalla Bibbia, Dio ha impiegato sei giorni per realizzare l'universo. Precedentemente, Chuck Norris aveva creato Dio schioccando le dita.",
"Si narra che la leggenda delle dodici fatiche di Ercole sia in realta' il remake di una storia meno nota ma comunque ricca di pathos, Le dodici passeggiate di salute di Chuck Norris.",
"Sono Tutti pazzi per Mary, tranne Chuck Norris.",
"Sting riesce a fare sesso per dodici ore di fila. Chuck Norris riesce a non fare sesso per dodici ore di fila.",
"Tempo fa Chuck Norris diede un calcio rotante cosi' forte a Cassius Clay che gli fece cambiare nome e religione.",
"Tempo fa, da McDonald's, lanciarono un hamburger ad edizione limitata: il McChuckNorris. Ingredienti: tranci di carne di vittima di calcio rotante di Chuck Norris, sangue di vittima di calcio rotante di Chuck Norris, lattuga e cetrioli. La gente chiedeva sempre di poterlo avere senza cetrioli. Il menu' bambini comprendeva anche un simpatico pupazzo di Spongebob.",
"Tra i gadget del coltellino svizzero di Chuck Norris c'e' Mac Gyver.",
"Tu hai preso la patente a diciotto anni. Chuck Norris a sedici. Secondi.",
"Un giorno Chuck Norris cavalco' un grizzly di tre metri in un autolavaggio, invece di farsi la doccia.",
"Un giorno Chuck Norris chiese ad una persona dov'era la palestra, questa glielo indico', e Chuck Norris le sferro' un calcio rotante in pieno volto per avergli detto cosa fare.",
"Un giorno Chuck Norris disse 'Kung'. E Kung Fu.",
"Un giorno Chuck Norris ha avuto un attacco di cuore. In tutta risposta, ha colpito il suo cuore con un calcio rotante per aver osato attaccare Chuck Norris.",
"Un giorno Chuck Norris ha mangiato il campione mondiale di mangiamento di hot dog. Per proprieta' transitiva, dunque, ora e' lui il campione in carica.",
"Un giorno Chuck Norris ha mangiato le palle di Mozart.",
"Un giorno Chuck Norris ha preso il treno, e se l'e' portato in camera.",
"Un giorno Chuck Norris ha sbadigliato e si e' estinto il dodo.",
"Un giorno Chuck Norris ha spaccato in due la Terra con un calcio rotante solo per vedere che sorpresa c'era dentro.",
"Un giorno Chuck Norris si e' spezzato una gamba con un calcio rotante per poter partecipare alle Paraolimpiadi e vincerle.",
"Un giorno Chuck Norris e' uscito di casa con un'erezione enorme. Non ci sono sopravvissuti.",
"Un giorno Cupido scaglio' una freccia verso Chuck Norris. Chuck Norris reagi' colpendo Cupido con un calcio rotante, uccidendo lui ed eliminando per sempre l'amore.",
"Un giorno Germano Mosconi ha bestemmiato Chuck Norris. E' stato licenziato sul posto. Con un calcio rotante.",
"Un giorno un avversario di Chuck Norris ha schivato un calcio rotante. E' comunque morto, decapitato dallo spostamento d'aria.",
"Un giorno un cinghiale impazzito si e' lanciato contro Chuck Norris: lui lo ha  preso e ci ha pitturato una parete grande.",
"Un giorno un rapinatore si avvicino' a Chuck Norris. Puntandogli una pistola contro, gli grido': 'O i soldi o la vita!'. Chuck Norris, dopo una breve riflessione, rispose: 'Per ora mi accontendo dei soldi'.",
"Un giorno un tizio ha chiesto a Chuck Norris se il suo vero nome fosse Charles. Chuck non ha risposto, ha solo fissato il tizio fino a quando costui non e' esploso.",
"Un giorno una ragazza offri' un Kinder Bueno a Chuck Norris. Ciccia e brufoli furono ritrovati il giorno dopo in un vicolo col collo spezzato.",
"Un giorno, dopo aver sentito 'I will survive', Chuck Norris decapito' Gloria Gaynor con un calcio rotante: l'aveva interpretata come una sfida.",
"Un giorno, in un supermercato, Chuck Norris ha proposto ad un passante due fustini di detersivo tradizionale in cambio di uno di Dash. Il passante ha accettato entusiasta.",
"Un giorno, mentre partecipava al Grande Fratello VIP, Chuck Norris e' stato  nominato. In un batter di ciglia, aveva sterminato tutti i suoi coinquilini.  Nessuno nomina Chuck Norris invano. Nessuno.",
"Un tizio in un forum ha scritto di questo blog: 'Che tristezza gli autori di questo blog, fanno venire dubbi sul destino della specie umana' o qualcosa del genere. Chuck Norris non ha gradito. Il destino di costui ora si trova spappolato vicino all'impronta di Armstrong. Sulla luna.",
"Una leggenda metropolitana vuole che il Paul McCartney che tutti conosciamo altro non sia che un sosia dell'originale, morto nel '66 in un incidente stradale. Nulla di piu' falso: il Paul McCartney attuale e' infatti il sosia del sosia dell'originale, morto nel '70 dopo un fortuito incontro con Chuck Norris e il suo calcio rotante.",
"Una notte Chuck Norris ha morso Dracula sul collo trasformandolo in un Chuck Norris.",
"Una notte, durante un temporale, Chuck Norris e' stato colpito da un fulmine. Il fulmine e' morto sul colpo.",
"Una notte, guardando il cielo, Chuck Norris ha unito i puntini da uno a 700.000.000.000.000.000.000.000. Accortosi che il risultato era un suo ritratto, decise di abolire i segni zodiacali. Ogni essere umano vivente, dunque, e' del segno del Chuck Norris.",
"Una regola poco nota del gioco della dama prevede che, dopo aver fatto tre volte il giro completo del tabellone, una vostra Dama possa aggiungere una terza pedina in cima. La combinazione ottenuta e' nota come 'Chuck Norris', e vi permettera' di prendere a calci rotanti tutte le pedine nel raggio di 6km.",
"Una volta Chuck Norris giocando a curling ha spazzolato talmente forte il ghiaccio che ha rinvenuto 4 mammuth e 3 uomini di Neanderthal.",
"Una volta Chuck Norris ha posato nudo per un'opera d'arte. La Colonna Traiana.",
"Una volta Chuck Norris ha rapito gli alieni.",
"Una volta Chuck Norris trovo' un degno avversario, dopo aver visto in tv il primo episodio della saga di Superman. Decise di sfidarlo, e il risultato fu Cristopher Reeve paralizzato in carrozzella.",
"Una volta Chuck Norris e' andato a vedere un porno al cinema ed e' venuto in maniera talmente prorompente da raggiungere lo schermo col seme ed ingravidare la protagonista.",
"Una volta Jean-Claude Van Damme ha ricevuto un'email da parte di Chuck Norris. Conteneva un allegato. Jean-Claude Van Damme l'ha aperto, e ha ricevuto un calcio rotante sui denti.",
"Una volta il mostro di Lochness ha fotografato Chuck Norris.",
"Una volta una ragazza ha spezzato il cuore di Chuck Norris. Lui, in risposta, le ha spezzato il collo.",
"Una volta, al Mugello, Valentino Rossi era ai 180 Km/h in curva e si e' sentito battere la spalla. Era Chuck Norris su un triciclo in impennata con una mano sola. Con l'altra teneva Max Biaggi.",
"Una volta, nei dintorni di El Paso, Chuck Norris fu assalito da uno sciame di vespe.",
"Uno studio ha rivelato che le principali cause di morte negli Stati Uniti sono:",
"Uri Geller e' stato in grado di piegare a meta' un cucchiaio con la forza del pensiero. Chuck Norris e' stato in grado di piegare a meta' Uri Geller con la forza del pensiero."
};

}
